module.exports = [
  {
    id: 1,
    item_name: "Salary Deposit",
    amount: 25000,
    date: "10-1-23",
    from: "Business",
    category: "Income",
    isPositive: true,
  },
  {
    id: 2,
    item_name: "Savings Deposit",
    amount: 15000,
    date: "10-1-23",
    from: "Personal",
    category: "Savings",
    isPositive: true,
  },
  {
    id: 3,
    item_name: "Grocery Shopping",
    amount: 125,
    date: "10-8-23",
    from: "Grocery Store",
    category: "Food & Groceries",
    isPositive: false,
  },
  {
    id: 4,
    item_name: "Credit Card Payment",
    amount: 500,
    date: "10-8-23",
    from: "Bank",
    category: "Card Payments",
    isPositive: false,
  },
  {
    id: 5,
    item_name: "Niece's Birthday Gift",
    amount: 250,
    date: "10-15-23",
    from: "Personal",
    category: "Gifts",
    isPositive: false,
  },
  {
    id: 6,
    item_name: "Takeout",
    amount: 30,
    date: "10-21-23",
    from: "Delivery App",
    category: "Food & Groceries",
    isPositive: false,
  },
  {
    id: 7,
    item_name: "Friend's Birthday Gift",
    amount: 350,
    date: "10-21-23",
    from: "Personal",
    category: "Gifts",
    isPositive: false,
  },
  {
    id: 8,
    item_name: "Salary Deposit",
    amount: 7500,
    date: "10-26-23",
    from: "Business",
    category: "Income",
    isPositive: true,
  },
];
